phraseapp:
  project_id: 8e1da11a577bc4eb2ca0a2b4011d165d
  push:
    sources:
    - file: /tmp/airmap.sdk.en.cleaned.xliff
      params:
        locale_id: en
        update_translations: true
        update_descriptions: true
        convert_emoji: true
        file_format: xlf
        tags: ios
  pull:
    targets:
    - file: /tmp/airmap.sdk.<locale_code>.translated.xliff
      params:
        convert_emoji: true
        file_format: xlf
        tags: ios
        format_options: { convert_placeholder: true }
